 site_name: Art & Object Marketplace Help Center
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: grey
      accent: red
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: grey
      accent: red
nav:
  - Home: 'index.md'
  - User Agreement: 'terms.md'
  - FAQs: 'faq.md'
  - Seller Tutorials: 'sellertuor.md'
  - Buyer Tutorials: 'buyertutor.md'
